server:
  port: 8082
spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/booking_hotel
    driver-class-name: com.mysql.jdbc.Driver
  security:
    jwt:
      secret-key: 4545454434324326737432864237498327493274983274893274893793773298
      expire-length: 3600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
