server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/booking_hotel
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
